openforcefield/qca-dataset-submission

- util/generate_cmiles_attributes.py
This small utility is able to generate the molecule `attributes` field, which is required by nearly everywhere dealing with QCSchema, and is required for dataset submission. Showing the CLI help below; it has a simple API to allow plugging the results into a dataset during submission.
```
usage: generate_cmiles_attributes.py [-h] [--use-rdkit] [--use-openeye]
input_json
Generates CMILES data for use with QCArchive when connectivity is not known.
Requires cmiles, the openff toolkit, OpenEye for protomers, RDkit for the
other attributes, and openbabel
positional arguments:
input_json     input file in json format. The json should be a list of
QCSchema-style symbols and coordinates (in bohr). A
dict(geometry=xyz, symbols=syms) is all that is needed for
each molecule.
optional arguments:
-h, …
```
> Add utility to generate CMILES info for dataset submission when connectivity is absent

- .github/workflows/prod-envs.yml
- devtools/conda-envs/anaconda-client-env.yaml
- devtools/docker/README.md
- devtools/docker/qcarchive_worker_openff/Dockerfile
- devtools/docker/qcarchive_worker_openff/docker-compose.test.yml
- devtools/prod-envs/README.md
- devtools/prod-envs/qcarchive-worker-openff.yaml
- devtools/prod-envs/qcarchive_worker_openff.yaml
Starting with #119 we will be performing MM calculations using QCArchive, which requires use of the following packages:
- openforcefield
- openforcefields
- openmm
- openmmforcefields
These dependencies can move quickly and require adjustment based on our (OpenFF's) activities, so we are moving the conda env file for our production workers to this repository.
As part of this PR, we also want to set up Github Actions CI that pushes changes to files in the `prod-envs` directory on `master` automatically to the Anaconda Cloud. This will require an OpenFF org similar to that for [QCArchive](https://anaconda.org/qcarchive).
Likewise, we want to build and push Docker images via Github Actions for new versions of these files. This PR includes a Dockerfile for building an image using the given …
> Added prod-envs, starting with qcarchive_worker_openff.yaml

- management/lifecycle.py
It looks like the management script was only keeping track of the errored torsiondirves for the last specification it checks this is now changed to capture all records making sure all torsiondrives are restarted across all specs.
> Torsiondrive restart fix.

- .github/workflows/prod-envs.yml
- devtools/prod-envs/qcarchive-worker-openff-ani.yaml
- devtools/prod-envs/qcarchive-worker-openff-openmm.yaml
- devtools/prod-envs/qcarchive-worker-openff-psi4.yaml
- devtools/prod-envs/qcarchive-worker-openff.yaml
We have recently found cases where certain libraries in our conda environment installs can conflict with one another in their dependencies, especially across different channels. To mitigate this in our production QCArchive worker environments, we have decided to create separate environments for different task types, namely:
- MM (OpenMM, openforcefield, ambertools, etc.)
- QM (psi4, dftd3, gcp, etc.)
- ML (torchani, pytorch)
This PR adds these production environments. It also updates the existing `qcarchive-worker-openff.yaml` environment currently used for QM+MM deployments, which currently covers common workload types we are computing. We have decided to pin our MM dependencies to specific versions so we can deliberately choose when to upgrade these in production.
> Added individual prod environments for different QCEngine harnesses

- submissions/2019-07-25-phenyl-set/README.md
- submissions/2019-07-25-phenyl-set/compute.json
This PR expands the existing "OpenFF Substituted Phenyl Set 1" TorsionDrive dataset to include additional compute specs. We include the following here:
- default (already computed)
- openff-1.0.0
- openff-1.2.0
- openff-1.2.1
- gaff-2.11
----
> Added supplemental compute spec to OpenFF Substituted Phenyl Set 1

- devtools/prod-envs/qcarchive-worker-openff-ani.yaml
- devtools/prod-envs/qcarchive-worker-openff-openmm.yaml
- devtools/prod-envs/qcarchive-worker-openff-psi4.yaml
- devtools/prod-envs/qcarchive-worker-openff-xtb.yaml
- devtools/prod-envs/qcarchive-worker-openff.yaml
This PR updates all prod environments to use `qcfractal 0.14.0` explicitly, as well as pinning to the latest versions of `openforcefield`, `openforcefields` where used.
A QCEngine release may be imminent, so we will wait for word on this before merge and deployment. That will give us improvements for both the Psi4 and ANI harnesses that we really want for production use.
> Updated prod envs to use qcfractal 0.14.0, latest openff packages

- management/validation.py
- submissions/2020-07-27-OpenFF-Benchmark-Ligands/README.md
- submissions/2020-07-27-OpenFF-Benchmark-Ligands/compute_xtb.json
This PR adds an xtb compute JSON which expands the fragmented benchmark ligands set.
> xtb Compute for the fragmented ligand set.

- devtools/prod-envs/qcarchive-worker-openff-openmm.yaml
- devtools/prod-envs/qcarchive-worker-openff.yaml
Currently we get the 20.9 `ambertools` conda package for the `qcarchive-worker-openff-openmm` environment, but 17.0 for the `qcarchive-worker-openff` env with "everything".
The pinning added in this PR yields the 17.0 conda package consistently. Confusingly, this appears to still give us the version 20.0 of tools such as `antechamber`. We may desire consistency over anything else here; discussion welcome!
> Pinning ambertools to 20.4 for prod envs with MM

- submissions/2020-07-27-OpenFF-Benchmark-Ligands/README.md
- submissions/2020-07-27-OpenFF-Benchmark-Ligands/compute_ani2x_maxiter.json
Adds a new `compute_ani2x_maxiter.json` file with a new ANI2X spec with more iterations. This is in effort to examine if we can get more successful calculations, since the current spec with 300 iterations produced many failures.
Everything in this update is the same otherwise, including molecules, etc.
> [2020-07-27-OpenFF-Benchmark-Ligands] add a new ANI2X spec with more iterations

- devtools/prod-envs/qcarchive-worker-openff-ani.yaml
- devtools/prod-envs/qcarchive-worker-openff-openmm.yaml
- devtools/prod-envs/qcarchive-worker-openff-psi4.yaml
- devtools/prod-envs/qcarchive-worker-openff-xtb.yaml
- devtools/prod-envs/qcarchive-worker-openff.yaml
I updated pins for all packages to latest released versions, except ambertools (left pinned at 20.4; #149).
We need a recommendation on which `linux-64` conda package to pin to for `psi4`: https://anaconda.org/psi4/psi4/files
> [prod-env-pin-update] Updated production env package pins for qcfractal 0.15.1

- devtools/prod-envs/qcarchive-worker-openff-ani.yaml
- devtools/prod-envs/qcarchive-worker-openff.yaml
Latest pytorch can break e.g. psi4 due to requiring a substitute `dataclasses` package for the standard lib one. Using 1.6.0 doesn't do this.
> Downgrading pytorch from 1.7.0 to 1.6.0 for prod envs

- submissions/2020-09-18-OpenFF-Sandbox-CHO-PhAlkEthOH/compute.json
> Added MM compute specs to CHO sandbox dataset

- devtools/conda-envs/error-cycle.yaml
- devtools/conda-envs/queued-submit.yaml
- devtools/conda-envs/validation.yaml
Update to the new qcsubmit conda package which should fix errors when we try to add specifications which are already present in a dataset.
> Update to the new qcsubmit conda package.

- submissions/2020-10-26-PEPCONF-Optimization/README.md
- submissions/2020-10-26-PEPCONF-Optimization/compute.json
> [PEPCONF] Add WB97X/6-31G* QC spec

- submissions/2020-10-06-OpenFF-Phenyl-Set/README.md
- submissions/2020-10-06-OpenFF-Phenyl-Set/compute.json
This PR is a re-do of #161; because I squash merged that PR's base, it wasn't possible to merge `master` back into it without a mess.
> MM compute for OpenFF Substituted Phenyl Set 1 v2.0 - reroll

- devtools/conda-envs/error-cycle.yaml
- devtools/conda-envs/queued-submit.yaml
- devtools/conda-envs/validation.yaml
- devtools/prod-envs/qcarchive-worker-openff-ani.yaml
- devtools/prod-envs/qcarchive-worker-openff-openmm.yaml
- devtools/prod-envs/qcarchive-worker-openff-psi4.yaml
- devtools/prod-envs/qcarchive-worker-openff-xtb.yaml
- devtools/prod-envs/qcarchive-worker-openff.yaml
Updated the following packages across all environments:
- qcsubmit=0.1.1 -> openff-qcsubmit=0.2.0
- qcfractal=0.15.1 -> 0.15.2
- openforcefield=0.8.0 -> 0.8.3
- openmm=7.4.2 -> 7.5.0
Added to prod envs with psi4:
- gau2grid=2.0.3
Leaving in place, despite possible package updates (discuss):
- ambertools=20.4
- psi4=1.4a2.dev1058+670a850
> Updates to prod-envs, GHA conda envs

- submissions/2020-10-26-PEPCONF-Optimization/README.md
- submissions/2020-10-26-PEPCONF-Optimization/compute-dlc.json
> [pepconf-dlc] Added default-dlc compute spec to PEPCONF dataset

- devtools/prod-envs/qcarchive-user-submit.yaml
Moved @pavankum's user submission environment to `prod-envs`, denoting it as a production resource. This is designed as a standard starting environment for preparing submissions, which we maintain to keep pins up-to-date with current practice and packages.
> Added qcarchive-user-submit production environment

- submissions/2021-06-04-OpenFF-Industry-Benchmark-Season-1-v1.1/compute.json
> Added MM compute expansion for OpenFF Industry Benchmark Season 1 v1.1

- submissions/2020-12-18-OpenFF-Theory-Benchmarking-Set-v1.0/compute.json
> added compute spec

- devtools/conda-envs/error-cycle.yaml
- devtools/conda-envs/queued-submit.yaml
- devtools/conda-envs/validation.yaml
- management/lifecycle.py
- management/validation.py
This PR updates the management utilities to use the latest version of QCSubmit (now on C-F). In particular: 
* The latest version introduced a number of API changes (mainly `dataset_type` was renamed to  just `type`) which are resolved here.
* The full stack is now on C-F so the omnia channel is now dropped.
* All references to `openforcefield` are now replaced with `openff.toolkit`.
Closes #212
> Update to latest `openff-qcsubmit` version

- devtools/prod-envs/qcarchive-worker-openff-openmm.yaml
- devtools/prod-envs/qcarchive-worker-openff.yaml
`openff-forcefields` 2.0.0 was released this week. This PR adds production env support for use of Sage in MM computations.
> Update prod envs to use openff-forcefields 2.0.0

- management/lifecycle.py
This PR will sync up submissions and compute expansions to allow errors assuming they to be expected during computing. This is useful for adding specs containing ani to datasets with missing element coverage.
> Dataset submission errors 

- submissions/2020-09-16-OpenFF-Protein-Fragments-TorsionDrives/README.md
Updates `2020-09-16-OpenFF-Protein-Fragments-TorsionDrives/README.md` with a warning about incorrect stereochemistry assignments in the inputs.
> Update protein dataset README to indicate incorrect chirality.

- devtools/conda-envs/backlog.yaml
- devtools/conda-envs/error-cycle.yaml
- devtools/conda-envs/queued-submit.yaml
- devtools/conda-envs/validation.yaml
- devtools/prod-envs/qcarchive-user-submit.yaml
- devtools/prod-envs/qcarchive-worker-openff-ani.yaml
- devtools/prod-envs/qcarchive-worker-openff-openmm.yaml
- devtools/prod-envs/qcarchive-worker-openff-psi4.yaml
- devtools/prod-envs/qcarchive-worker-openff-xtb.yaml
- devtools/prod-envs/qcarchive-worker-openff.yaml
Using python 3.8, latest of all packages except:
- psi4, as next is major version 1.5, which we may want to validate
before production deployment
- pytorch, as torchani 2.2 uses it, and still no new relese of that
package
> Prod env update

- .github/workflows/lifecycle-backlog.yml
- .github/workflows/lifecycle-error-cycle.yml
- .github/workflows/lifecycle-set-priority-computetag.yml
- .github/workflows/lifecycle-submission.yml
- .github/workflows/prod-envs.yml
- .github/workflows/validation.yaml
github actions are failing because the workflow scripts had python version set to 3.7
> update python version on workflows

- management/validation.py
Validation was failing for compute spec addition since the argument extras was missing from `create_spec_report()` under `check_compute_request()`
> valid_scf_props argument added under compute spec check

- devtools/conda-envs/validation.yaml
Update validation env to include openmm and pin pint to < 0.20.
> update validation env to include openmm

- devtools/prod-envs/qcarchive-user-submit.yaml
- devtools/prod-envs/qcarchive-worker-openff-ani.yaml
- devtools/prod-envs/qcarchive-worker-openff-openmm.yaml
- devtools/prod-envs/qcarchive-worker-openff-xtb.yaml
We cannot use 0.25.0 alongside psi4 until a new release of psi4 is made.
psi4 1.6.1 only allows for qcengine >=0.23.0 <0.25.
However, we want to proceed with qcengine 0.25.0 for OpenMM use, since
this is compatible with openff-toolkit >= 0.11.0.
> Upping qcengine to 0.25.0, qcelemental to 0.25.1 for non-psi4 prod envs

- devtools/docker/qcarchive-worker-openff/Dockerfile
See title; hitting what appear to be memory issues in build for openff docker image.
Switching to mamba to address this.
> Attempt to perform Docker build with mamba to avoid memory issues from conda

- management/lifecycle.py
Fixes #358 by adding two unused arguments to the function, in line with the other execute_state functions.
> Add unused arguments to execute_requires_scientific_review

- devtools/conda-envs/error-cycle.yaml
- devtools/conda-envs/queued-submit.yaml
- devtools/conda-envs/validation.yaml
Update the automation environments to use the latest qcsubmit versions which should allow the MLPepper dataset to submit, see failed attempt [here](https://github.com/openforcefield/qca-dataset-submission/actions/runs/10380312200/job/28739926732).
> Update automation environments

- .github/workflows/lifecycle-error-cycle.yml
- management/README.md
- management/lifecycle.py
- management/projectsv2.py
Update project board fetching to use GraphQL interface so we can run error cycling. 
This doesn't handle board modification yet.
> Fix error cycling

- .github/workflows/test-lifecycle.yaml
We need to merge CI files into master before they can be run, so adding a test file for the overhaul I'm trying in #375.
> Add test CI

- management/lifecycle.py
#375 made the bot overly verbose and leave comments on the current state of the card. This PR gets the bot to only comment if something has changed.
> Remove unnecessary bot comments

- .github/workflows/lifecycle-error-cycle.yml
- .github/workflows/lifecycle-set-priority-computetag.yml
As covered in [this comment](https://github.com/openforcefield/qca-dataset-submission/pull/408#issuecomment-2489455218), retagging individual records is really handy for subdividing datasets based on molecule size to make requesting NRP workers easier, but the current lifecycle actions automatically retag ~6 times per day (5 from the retag action itself and 1 from error cycling), disrupting any manual tagging done as described in the comment.
I think these changes should prevent all automatic retagging. One remaining issue is that anyone manually running the retag action to update their dataset tag will still overwrite any of these subset tags, but at least that's likely to happen fewer than 6 times daily.
> Don't retag automatically in lifecycle workflows

- management/lifecycle.py
- management/test_lifecycle.py
This implements the feature discussed in #408, where labels beginning with `compute-` (this is enforced by the original code) and ending with `_mw-300-600-900`, just for example, the numbers can be anything, will be split up and tag separate portions of the dataset based on molecular weight. For example, `compute-openff_mw-100-200-300` will cause the creation of four tags: `compute-openff-100` for MW < 100, `compute-openff-200` for 100 <= MW < 200, `compute-openff-300` for 200 <= MW < 300, and `compute-openff-large` for anything larger than 300 Da. I wrote the splitting code in a generic way, so it should also handle  different numbers of groups other than 3, for example `_mw-300` or `_mw-100-200-300-400-500`.
For tags that don't match the pattern, the usual behavior should be preserved, …
> Split dataset tags based on PR labels

- management/lifecycle.py
This fixes an issue where importing qcelemental at the top level breaks lifecycle.py in environments without qcel installed.
> Only import qcelemental for type checking

- management/lifecycle.py
Follow up to #414  -- the | operator isn't supported with strings.
> Change to old-style typing in lifecycle.py

- devtools/conda-envs/error-cycle.yaml
- devtools/conda-envs/queued-submit.yaml
- devtools/conda-envs/validation.yaml
Pinned the version of `openff-units` in the validation environment to avoid import error described in #429 . Fixes #429 for me locally, but I can't run the full validation locally due to missing a github token.
> Updating validation environment to update units package

- archival/Dockerfile
- archival/dataset_handling_optimization_v1.0.ipynb
- archival/dataset_handling_singlepoint_v1.0.ipynb
- archival/dataset_handling_torsiondrive_v1.0.ipynb
Update the archival materials to include notebooks for single datasets, either torsiondrive, optimization, or singlepoint.
- The optimization notebook is identical to the optimization portion of the original notebook, with the addition of a try/except statement to find the CMILES information.
- The torsiondrive notebook is identical to the optimization portion of the original notebook, with an alteration of the printed energies at the end.
- The singlepoint notebook is based on the optimization notebook with alterations in attribute names for functionality.
> Add notebooks for each dataset type

- management/lifecycle.py
Closes #437.
These changes will allow a scaffold.json to be submitted to QCArchive. Should not be merged until #438 is resolved.
> Add scaffold submission to lifecycle
