- 6-25-19-smirnoff99Frost-coverage/create_optimization_dataset.py
@dgasmith I just realized that the previous submit script does not set the CMILES ids as attributes of the records in OptimizationDataset.
This PR adds that feature, so it's consistent with the previously submitted datasets.
> add cmiles_ids as attributes to each record of OptimizationDataset

- 2019-07-02 VEHICLe optimization dataset/04_create_hessian_dataset.py
- 2019-07-09-OpenFF-Optimization-Set/04_create_hessian_dataset.py
For these very large dataset we go around the current construction tech. I have this ear marked to update in the primary portal branch. This should close #24 and adds a small stub for #16.
> Hessian script for VEHICLe and Optimization Set 1

- 2019-06-25-smirnoff99Frost-coverage/02_create_optimization_dataset.py
This PR updates the optimization keywords to improve convergence.
As discussed on slack: https://openforcefieldgroup.slack.com/archives/CJQ4DCWN8/p1563726947037100
> update geometric input options for faster convergence

- 2019-06-25-smirnoff99Frost-coverage/04_create_hessian_dataset.py
- 2019-07-05 eMolecules force field discrepancies 1/02_create_optimization_dataset.py
Submits coverage set, closes #33.
> Coverage Hessian Submission

- 2019-07-05 OpenFF NCI250K Boron 1/04_create_hessian_dataset.py
- 2019-07-05 eMolecules force field discrepancies 1/04_create_hessian_dataset.py
Submits the Boron and eMolecules Hessian computations.
> eMolecules Hessians

- 2020-04-28-Fragmenter-test/04_add_additional_specs.py
This adds several new chemistry models in order to explore their effects on charged molecules, such as those in this small dataset.
> add additional chemistry models to "2020-04-28-Fragmenter-test"

- README.md
- STANDARDS.md
> Dataset submission guidelines/standards 

- submissions/2020-03-23-OpenFF-Gen-2-Torsion-Set-1-Roche-2/spec.json
Needed for automation.
We are using this as a test case for automation via Github Actions.
> OpenFF Gen 2 Torsion Set 1 Roche 2 - tracking

- submissions/2020-03-23-OpenFF-Gen-2-Torsion-Set-2-Coverage-2/spec.json
This is required for plugging this dataset into tracking automation.
> OpenFF Gen 2 Torsion Set 2 Coverage 2 - tracking

- .github/pull_request_template.md
I have included a PR template with instructions, are there any others we should add? @dotsdl @trevorgokey ?
> Add a pull request template with instructions.

- management/lifecycle.py
- management/management.py
Adds regeneration of hanging INCOMPLETE tasks to automated error cycling.
> Added Optimization regeneration for stalled INCOMPLETEs

- devtools/conda-envs/queued-submit.yaml
- devtools/conda-envs/validation.yaml
- management/validation.py
This will update the validation and submission environments to use the latest QCSubmit package `v0.1.0` which includes PCM support. The validation report is also updated to include this in the specification print out. The conda envs are also changed to use the basis set exchange conda-forge package.
> Validation Update

- devtools/conda-envs/user-submit.yaml
> general purpose conda env for user submissions

- README.md
- README_old.md
just concatenated lifecycle and index files
> first iteration to change README.md

- .github/workflows/lifecycle-error-cycle.yml
- .github/workflows/lifecycle-set-priority-computetag.yml
- README.md
- management/lifecycle.py
This is a similar mechanism to label-based priority setting.
We will need to create an action that utilizes it, perhaps running periodically as we do with prioritization.
> Added label-based compute tagging to lifecycle

- .github/workflows/prod-envs.yml
- devtools/prod-envs/qcarchive-user-submit.yaml
- devtools/prod-envs/qcarchive-worker-openff-ani.yaml
- devtools/prod-envs/qcarchive-worker-openff-openmm.yaml
- devtools/prod-envs/qcarchive-worker-openff-psi4.yaml
- devtools/prod-envs/qcarchive-worker-openff-xtb.yaml
- devtools/prod-envs/qcarchive-worker-openff.yaml
In particular, psi4 1.4 is out.
Also want to use new namespace packages for toolkit, others.
> Updates to all production environments given new packages

- management/validation.py
This PR adds a try-except block when removing the scf_properties which I missed on #224 and will now print the index of any entries which fail validation.
> Validation update2

- devtools/conda-envs/error-cycle.yaml
- devtools/conda-envs/queued-submit.yaml
To resolve submission error with #220
> bump qcsubmit version to 0.2.3

- devtools/conda-envs/error-cycle.yaml
- devtools/conda-envs/queued-submit.yaml
- devtools/conda-envs/validation.yaml
Bump all management envs to use qcsubmit 0.3.0
> bump qcsubmit to 0.3.0

- submissions/2021-11-08-QMDataset-pubchem-set1-single-points/README.md
> SPICE PubChem Set 1 Single Points Dataset v1.2

- submissions/2021-11-09-QMDataset-pubchem-set2-single-points/README.md
> SPICE PubChem Set 2 Single Points Dataset v1.2

- submissions/2021-11-09-QMDataset-pubchem-set3-single-points/README.md
> SPICE PubChem Set 3 Single Points Dataset v1.2

- submissions/2021-11-09-QMDataset-pubchem-set4-single-points/README.md
> SPICE Pubchem Set 4 Single Points Dataset v1.2

- submissions/2021-11-09-QMDataset-pubchem-set5-single-points/README.md
> SPICE PubChem Set 5 Single Points Dataset v1.2

- submissions/2021-11-09-QMDataset-pubchem-set6-single-points/README.md
- submissions/2021-11-09-QMDataset-pubchem-set6-single-points/dataset-v1.2.json.bz2
> SPICE PubChem Set 6 Single Points Dataset v1.2

- .github/workflows/lifecycle-backlog.yml
- management/lifecycle.py
This will aid in searchability for submissions that are complete vs. those that are not.
> Added tagging of PRs based on post-compute status

- submissions/2021-11-08-QMDataset-DES370K-single-points/compute.json
> SPICE DES370K Openff default spec

- submissions/2021-11-08-QMDataset-Dipeptide-single-points/compute.json
> SPICE Dipeptide single points Openff default

- submissions/2021-11-08-QMDataset-Solvated-Amino-Acids-single-points/compute.json
> SPICE Solvated Amino Acids single points Openff default

- submissions/2021-11-08-QMDataset-pubchem-set1-single-points/compute.json
> SPICE Pubchem set 1 Openff default

- submissions/2021-11-09-QMDataset-pubchem-set2-single-points/compute.json
> SPICE Pubchem set 2 Openff default

- submissions/2021-11-09-QMDataset-pubchem-set3-single-points/compute.json
> SPICE Pubchem set 3 Openff default

- submissions/2021-11-09-QMDataset-pubchem-set4-single-points/compute.json
> SPICE Pubchem set 4 Openff default

- submissions/2021-11-09-QMDataset-pubchem-set5-single-points/compute.json
> SPICE Pubchem set 5 Openff default

- submissions/2021-11-09-QMDataset-pubchem-set6-single-points/compute.json
> SPICE Pubchem set 6 Openff default

- submissions/2022-06-08-QMDataset-ion-pairs/compute.json
> SPICE Ion Pairs Openff default

- submissions/2021-11-15-QMDataset-DES-monomers-single-points/compute.json
> SPICE DES Monomers Openff default

- .github/workflows/prod-envs-docker.yml
- .github/workflows/prod-envs.yml
- devtools/docker/qcarchive-worker-openff/Dockerfile
- devtools/prod-envs/qcarchive-user-submit.yaml
- devtools/prod-envs/qcarchive-worker-openff-ani.yaml
- devtools/prod-envs/qcarchive-worker-openff-openmm.yaml
- devtools/prod-envs/qcarchive-worker-openff-psi4.yaml
- devtools/prod-envs/qcarchive-worker-openff-xtb.yaml
Attempting to use latest packages, pinning where appropriate to create some degree of determinism over time for the most important packages when building prod instances from these environments.
> Updating prod envs for compute deployments

- .github/workflows/prod-envs-docker.yml
- .github/workflows/prod-envs.yml
- devtools/prod-envs/qcarchive-worker-openff-ani.yaml
@lilyminium noted that using pytorch 2.1.0 appears to solve with conda. Trying it here.
> Set pytorch to 2.1.0 for torchani env

- devtools/prod-envs/qcarchive-user-submit.yaml
- examples/OptimizationDataset/generate-dataset.ipynb
I used this dataset (`cp ../../submissions/2021-06-22-OpenFF-BCC-Refit-Study-COH-v2.0/molecules.smi .`) locally.
> Update and re-run dataset preparation example

- LICENSE
This PR adds a data license section to the LICENSE file.
> Add data license

- .github/workflows/lifecycle-backlog.yml
- .github/workflows/lifecycle-error-cycle.yml
- .github/workflows/lifecycle-set-priority-computetag.yml
- .github/workflows/lifecycle-submission.yml
- .github/workflows/prod-envs-docker.yml
- .github/workflows/prod-envs.yml
Part of #357 -- this updates the turnstyle action to point to master, instead of v1 which was released in 2020.
> Point turnstyle action to master

- NRP/README.md
- NRP/deployment_template.yaml
- NRP/manager_template.yaml
Increasing my bus factor by adding basic NRP usage document and templates. Big thanks to @dotsdl who provided the starting material for this.
> NRP onboarding

- submissions/2024-09-18-OpenFF-NAGL2-ESP-Timing-Benchmark-v1.1/README.md
- submissions/2024-09-18-OpenFF-NAGL2-ESP-Timing-Benchmark-v1.1/compute.json
- submissions/2024-09-18-OpenFF-NAGL2-ESP-Timing-Benchmark-v1.1/generate-compute.ipynb
> Add ddx to nagl benchmark

- README.md
Adding @lilyminium 's description of what happens when a compute expansion is submitted. Closes #398
> Update README.md with details about compute expansion

- submissions/2024-09-18-OpenFF-NAGL2-ESP-Timing-Benchmark-v1.1/README.md
- submissions/2024-09-18-OpenFF-NAGL2-ESP-Timing-Benchmark-v1.1/compute3.json
- submissions/2024-09-18-OpenFF-NAGL2-ESP-Timing-Benchmark-v1.1/generate-compute-nodiffuse.ipynb
> adding third compute expansion

- management/lifecycle.py
The error cycling CI requires expected a dict type from an OpenFF dataset, but if not provided, pulled a list of spec names from a dataset. This caused an error:
`AttributeError: 'list' object has no attribute 'keys'` in line 807 of lifecycle:
`for key, counts in status.items() if key in dataset_specs.keys()}`
Only a list of spec names is actually needed, so this PR revises that the list of spec names is always pulled from the dataset collection directly. 
This may not be the desired behavior if it's expected that a json file may contain a new spec, and that records involving old specs shouldn't be considered.
> Resolve consistent use of dataset_specs as a list of names.

- submissions/2025-03-17-Curated-tmQM-xtb-Dataset-T=100K-Dataset-Restricted-to-Pd-Zn-Fe-Cu-v0.0/scaffold.json.bz2
LSF object for scaffold.json.bz2 was not fully uploaded in merge of #445
> Update tmQM scaffold.json

- management/lifecycle.py
- management/test_lifecycle.py
Fixes #459 and also updates to compute_priority instead of priority
> add updated compute tag kwarg

- .github/workflows/prod-envs-docker.yml
- devtools/prod-envs/qcarchive-worker-openff-xtb.yaml
Update xtb docker image with new release of QCFractal.
> Update xtb docker image

- .github/workflows/validation.yaml
- devtools/conda-envs/validation.yaml
- management/lifecycle.py
- management/scaffold_validation.py
- management/validation.py
Add validation for scaffold datasets that bypass QCSubmit. 
Closes #438 
Tests were run in a notebook in [another repository](https://github.com/jaclark5/scaffold_validation)
> Scaffold validation

- management/README.md
We recently learned how to change our own password, this PR records that information for posterity.
> Update README.md for management

- .github/workflows/prod-envs-docker.yml
- devtools/prod-envs/qcarchive-worker-openff-psi4-basis-set-update.yaml
- devtools/prod-envs/qcarchive-worker-openff-psi4-ddx.yaml
- devtools/prod-envs/qcarchive-worker-openff-xtb.yaml
Updating docker images with new version of QCArchive
Closes #486
> Update docker yaml files

- devtools/conda-envs/error-cycle.yaml
- devtools/conda-envs/queued-submit.yaml
- devtools/conda-envs/validation.yaml
Close #485 
This PR Updates the yaml files for validation, submission, and error cycling.
> Update yaml files
